ftp/urls.py
from django.urls import path
from . import views
from .forms import UserLoginForm
from django.contrib.auth.decorators import login_required

app_name = "ftp"

urlpatterns = [
    path('', views.Home, name='home'),
    path("reg/", views.RegisterView.as_view(), name="register"),
    path("login/", views.LoginRequestView.as_view(),name="login-page"),
    path("logout/", views.LogoutRequestView.as_view(), name="logout-page"),
    path("dashboard/<str:pk>", views.Dashboard.as_view(), name="dashboard"),
    path("upload/<str:pk>", views.UploadView.as_view(), name="upload"),
    path("create_dir/",views.CreateFolder.as_view(), name="create-dir" ),
    path("create_sub_dir/<slug:pk>",views.CreateSubFolder.as_view(), name="create-sub-dir" ),
    path("display_folder/<slug:pk>",views.FolderView.as_view(), name="display_folder-page" ),
    path("profile/",views.ProfileView.as_view(), name="profile" ),
    path('about/', views.about_us, name='about'),
    path("del_folder/<slug:pk>",views.DeleteFolder.as_view(), name="delete-folder"),
    path("del_file/<slug:pk>/",views.DeleteFile.as_view(), name="delete-file"),
    path("all_files/<str:pk>/",views.ViewAllFiles.as_view(), name="view-all-files"),
    path("update_folder/<str:pk>/",views.FolderRenameView.as_view(), name="folder-rename"),
    path("update_file/<str:pk>/",views.FileRenameView.as_view(), name="file-rename"),
    path("change_password/",views.ChangePasswordView.as_view(), name="change-password"),
    path("search/<str:pk>",views.SearchView.as_view(), name="search"),
    path("trash/",views.TrashView.as_view(), name="trash"),
]

ftpHosting/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ftp.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ftp/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


# Create your models here.
def user_directory_path(instance, filename):
    return "%s%s" %(instance.user.username, filename)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=50, null=True)
    lastname = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.user.username

class Directory(models.Model):
    id=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    parent = models.ForeignKey('self', null=True, on_delete=models.CASCADE)
    is_deleted = models.BooleanField(default=False)

    def nfiles(self):
        files = self.myfiles_set.filter(is_deleted='False')
        n = files.count()
        return n

class MyFiles(models.Model):
    id=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    file_path = models.FileField(upload_to=user_directory_path)
    directory = models.ForeignKey(Directory, null=True, on_delete=models.CASCADE)
    file_name=models.CharField(max_length=50, default='file.txt')
    file_ext = models.CharField(max_length=10, default='.txt')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_deleted = models.BooleanField(default=False)


def create_profile(sender, instance, created, **kwargs):
    if created:
       user_profile = Profile(user=instance)
       user_profile.save()

post_save.connect(create_profile, sender=User)

ftp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
	First_Name = forms.CharField(widget=forms.TextInput(attrs={
		"class":"form-control form-control-user",
		"type":"text",
		"placeholder":"First Name",
	}))

	Last_Name = forms.CharField(widget=forms.TextInput(attrs={
		"class":"form-control form-control-user",
		"type":"text",
		"placeholder":"Last Name",
	}))

	username = forms.CharField(widget=forms.TextInput(attrs={
		"class":"form-control form-control-user",
		"type":"text",
		"placeholder":"Username",
	}))

	email = forms.CharField(widget=forms.TextInput(attrs={
		"class":"form-control form-control-user",
		"type":"email",
		"placeholder":"Email",
	}))
	
	password1 = forms.CharField(widget=forms.TextInput(attrs={
		"class":"form-control form-control-user",
		"type":"password",
		"placeholder":"Password..Min 8 characters",
	}))

	password2 = forms.CharField(widget=forms.TextInput(attrs={
		"class":"form-control form-control-user",
		"type":"password",
		"placeholder":"Re-enter Password",
	}))

	# class Meta:
	# 	model = User
	# 	fields = ("First_Name","Last_Name", "username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(RegisterForm, self).save(commit=True)
		user.email = self.cleaned_data['email']
		user.First_Name = self.cleaned_data['First_Name']
		user.Last_Name = self.cleaned_data['Last_Name']
		if commit:
			user.save()
		return user

class FileUpload(forms.Form):
	file = forms.FileField(label= 'Select a file')

class CreateDirForm(forms.Form):
   d_name = forms.CharField(max_length = 100)

class RenameDirForm(forms.Form):
	d_name = forms.CharField(max_length=20)

class RenameFileForm(forms.Form):
	d_name = forms.CharField(max_length=20)

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
			"class":"form-control form-control-user",
			"type":"text",
			"placeholder":"Username",
	}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
			"class":"form-control form-control-user",
			"type":"password",
			"placeholder":"Enter password",
	}))
    # class Meta:
    #     model = User
    #     fields = ('username', 'password')

class ChangePasswordForm(forms.Form):
	user_name =forms.CharField(widget=forms.TextInput(attrs={
		"class":"form-control form-control-user",
		"type":"text",
		"placeholder":"Enter Your Username",
	}))
	pass_word = forms.CharField(widget=forms.PasswordInput(attrs={
			"class":"form-control form-control-user",
			"type":"password",
			"placeholder":"Enter New password",
	}))
	# class Meta:
	# 	model = User
	# 	fields = ('username','password')
   

ftp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
from django.contrib.auth.models import User
from requests import delete
from .forms import RegisterForm, CreateDirForm, UserLoginForm,FileUpload, RenameDirForm, RenameFileForm, ChangePasswordForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
from ftp.models import  Directory, MyFiles, Profile
from django.core.files import File
from django.views.generic import DetailView, ListView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.views.generic.edit import FormView, CreateView
from django.urls import reverse_lazy, reverse
from django.utils.functional import lazy
import os

# Create your views here.

def Home(request):
    if request.user.is_authenticated:
        return redirect("ftp:dashboard",pk=request.user.username)

    return redirect("ftp:login-page")


class RegisterView(View):
    def get(self, request):
        form = RegisterForm()
        # pass
        return render(request, "ftp/register_new.html", context={"register_form": form})

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            uname = form.cleaned_data.get('username')
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("ftp:login-page")
        messages.warning(
            request, "Unsuccessful registration. Invalid data or Username already exists.")
        form = RegisterForm()
        return render(request, "ftp/register_new.html", context={"register_form": form})


class LoginRequestView(View):
    def get(self, request):
        form = UserLoginForm()
        return render(request, template_name="ftp/login_new.html", context={"login_form": form})

    def post(self, request):
        form = UserLoginForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("ftp:dashboard",pk=user.username)
            else:
                messages.warning(request, "Invalid username or password!!!")
                form = AuthenticationForm()
                return render (request, 'ftp/login_new.html', context={"login_form":form})
        else:
            messages.warning(request, "Invalid username or password!!!")
            form = UserLoginForm()
            return render (request, 'ftp/login_new.html', context={"login_form":form})


class LogoutRequestView(View):
    def get(self, request):
        logout(request)
        messages.info(request, "You have successfully logged out.")
        return redirect("ftp:home")


@method_decorator(login_required, name='dispatch')
class Dashboard(DetailView):
    model = Directory
    template_name = "ftp/dashboard.html"

    def get_queryset(self):
        uid = User.objects.get(username=self.request.user)
        self.queryset = Directory.objects.filter(user=uid).filter(is_deleted=False).filter(parent=None)
        return self.queryset

    def get(self, request,pk):
        context = self.get_queryset()
        return render(request,"ftp/dashboard.html", {'context':context,})


@method_decorator(login_required, name='dispatch')
class UploadView(FormView):
    form_class = FileUpload
    template_name = 'upload_file.html'
    success_url = 'ftp/display_folder.html'

    def post(self, request, pk):
        current_dir = Directory.objects.get(pk=pk)
        if request.FILES.get('myfile'):
            myfile = request.FILES.get('myfile')
            fs = FileSystemStorage()
            filename = fs.save(myfile.name, myfile)
            uploaded_file_url = fs.url(filename)
            obj = MyFiles()
            obj.file_name=filename
            file_extension= os.path.splitext(filename)[1]
            obj.file_ext=file_extension
            obj.file_path = uploaded_file_url
            obj.user = request.user
            obj.directory = current_dir
            obj.save()
            messages.success(request, "File uploaded successfully")
        else:
            f1 = MyFiles.objects.filter(directory=current_dir)
            messages.warning(request, "No file selected")
            return render(request, 'ftp/display_folder.html', {'pk': pk,'d':f1})
        f = MyFiles.objects.filter(directory=current_dir)
        return render(request, 'ftp/display_folder.html', {'pk': pk,'d':f})

    def get(self, request, pk):
        return render(request, 'ftp/upload_file.html' ,{'pk':pk})


@method_decorator(login_required, name='dispatch')
class CreateFolder(CreateView):
    model=Directory
    fields = ['name']

    def get(self, request):
        form = CreateDirForm()
        return render(request, 'ftp/create_dir.html', {'form':form})

    def post(self, request):
        my_form = CreateDirForm(request.POST)
        if my_form.is_valid():
            dname = my_form.cleaned_data['d_name']
            obj = Directory()
            if not self.if_folder_name_exists(dname):
                obj.user = request.user
                # obj.parent = pk
                obj.name = dname
                obj.save()
                messages.success(request, "Folder created successfully")
            else:
                messages.warning(request, "Folder already exists with this name. Try other name")
                # return redirect("ftp:dashboard",pk=pk)
                return redirect("ftp:dashboard",pk=request.user.username)


        uid = User.objects.get(username=self.request.user)
        context = Directory.objects.filter(user=uid).filter(is_deleted=False)
        return render(request, 'ftp/dashboard.html', {'context':context})

    def if_folder_name_exists(self, name):
        no_of_folders = Directory.objects.filter(name=name,is_deleted=False, user=self.request.user).count()
        if no_of_folders == 0:
            return False
        return True 
@method_decorator(login_required, name='dispatch')
class CreateSubFolder(CreateView):
    model=Directory
    fields = ['name']
    
    def get(self, request):
        form = CreateDirForm()
        return render(request, 'ftp/create_dir.html', {'form':form})

    def post(self, request, pk):
        my_form = CreateDirForm(request.POST)
        if my_form.is_valid():
            dname = my_form.cleaned_data['d_name']
            obj = Directory()
            if not self.if_folder_name_exists(dname):
                obj.user = request.user
                obj.parent = Directory.objects.get(pk=pk)
                obj.name = dname
                obj.save()
                messages.success(request, "Folder created successfully")
            else:
                messages.warning(request, "Folder already exists with this name. Try other name")
                # return redirect("ftp:dashboard",pk=pk)
                return redirect("ftp:display_folder-page",pk=pk)


        uid = User.objects.get(username=self.request.user)
        context = Directory.objects.filter(user=uid).filter(is_deleted=False)
        return render(request, 'ftp/dashboard.html', {'context':context})

    def if_folder_name_exists(self, name):
        no_of_folders = Directory.objects.filter(name=name,is_deleted=False, user=self.request.user).count()
        if no_of_folders == 0:
            return False
        return True
    
@method_decorator(login_required, name='dispatch')
class FolderView(View):
    def get(self, request, pk):
        directory = Directory.objects.get(pk=pk)
        # data = Directory.objects.filter(pk=pk).filter(user=request.user).filter(is_deleted='False').filter(parent=pk)
        fil = MyFiles.objects.filter(directory=directory).filter(is_deleted=False)
        sub_dirs = Directory.objects.filter(user=self.request.user, is_deleted=False, parent=pk)
        return render(request, 'ftp/display_folder.html', {'d':fil,'sub_dirs':sub_dirs, 'pk':pk})


@method_decorator(login_required, name='dispatch')
class ProfileView(ListView):
    model = Profile

    def get(self,request):
        p = Profile.objects.get(user=request.user)
        return render(request, 'ftp/profile.html', {'p':p})

@method_decorator(login_required, name='dispatch')
class DeleteFolder(DeleteView):
    model = Directory

    def get_success_url(self):
        u = self.request.user.username
        messages.info(self.request, "Folder deleted!!")
        return reverse_lazy('ftp:dashboard', kwargs={'pk':u})

    # def delete(self, request, *args, **kwargs ):
    #     self.object = self.get_object()
    #     success_url = self.get_success_url()
    #     print(self.object.name)
    #     #self.object.delete()
    #     self.object.is_deleted = True
    #     print("@@@@@@@@@@@@@@@")
    #     return redirect(success_url)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.is_deleted = True
        r_files = MyFiles.objects.filter(user=request.user).filter(directory= self.object)
        r_files.update(is_deleted=True)
        self.object.save()
        return redirect(success_url)

@method_decorator(login_required, name='dispatch')
class DeleteFile(DeleteView):
    model = MyFiles

    def get_success_url(self):
        o_id = self.kwargs.get('pk')
        dir = MyFiles.objects.get(id = o_id).directory
        folder_name = str(dir.name)

ftp/templates/ftp/directory_confirm_delete.html
<form method="post" action=" ">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

ftp/templates/ftp/logout.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="False" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
        
        <li class="nav-item">
          <a class="nav-link" href="/logout">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Welcome, {{user.username}}</a>
        </li>
  
        {% else %}
  
        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
  
        {% endif %}
      </ul>
    </div>
  </nav>

ftp/templates/ftp/myfiles_confirm_delete.html
<form method="post" action=" ">
    {% csrf_token %}
    <h1>Are you sure you want to delete "{{ object.file_path }}"?</h1><br>
    <input class="btn btn-danger" type="submit" value="Yes">
    <div class="btn btn-primary"><a href="{% url 'ftp:display_folder-page' object.directory.name %}" >Cancel</a></div>
</form>

ftp/templates/ftp/profile.html
{% extends 'ftp/base.html' %}
{% block content %}

    <div>
        
        <div>Username: {{p.user}}</div> 
   
    <br>
    <div>First Name: {{p.firstname}}</div> 
   
    <br>
    <div>Last Name: {{p.lastname}}</div> 
   
    <br>
    
        <div>Email: {{p.user.email}}</div> 
    </div>
  
{% endblock %}

ftp/templates/ftp/trash.html
{% extends "ftp/base.html" %}
{% load static %}

{% block content %}
<div class="row">
            {% if d or f %}
            {% for i in d %}
            <div class="col-sm-6 col-md-4 col-lg-3 col-xl-2">
                    
                <div class="col mr-2">
                    <div style="display: flex; flex-direction: column;">
                        <div class="container">
                            <a class=" dropdown-toggle" href="#" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: azure;">
                                <i class="fa fa-caret-down fa-2x" style="color: #6586E7; position: absolute; left: 60px;" aria-hidden="true"></i>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <a href="{% url 'ftp:delete-folder' pk=i.id %}" class="dropdown-item text-danger" data-toggle="modal" data-target="#del{{i.name}}" id="delete-item">              
                                    Delete
                                    <i class="fa fa-trash" aria-hidden="true" ></i>
                                </a>
                                <a href="{% url 'ftp:folder-rename' pk=i.name %}" class="dropdown-item text-info" data-toggle="modal" data-target="#edit{{i.name}}" id="edit-item">
                                Edit Name
                                <i class="fas fa-edit"></i>
                                </a>
                            </div>
                       </div>
                       <div>
                            <a href="#" >
                                <i class="fa-solid fa-folder" style="font-size: 4rem; color: #6586E7;"></i>
                            </a>
                        </div>
                        <span style="word-wrap: break-word;">
                           
                            {{ i.name }}
                            
                        </span>
                    </div>
                </div>
            </div>   
<!-- delete modal -->
<div class="modal fade" id="del{{i.name}}">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" style="color: rgb(43, 83, 197);">Folder Delete</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
            </div>
            <div class="modal-body">
                <p>Are you sure to delete folder {{i.name}}</p>
            </div>
            <div class="modal-footer">
                <div class="justify-content-between mb-2 mr-2 text-right">
                    <form method="post" id="item-delete-form" action="{% url 'ftp:delete-folder' pk=i.id %}">
                        <button type="button" class="btn btn-primary mr-1" data-dismiss="modal">Cancel</button>
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger" id="confirm-delete-item-button">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- edit folder modal-->
<div class="modal fade" id="edit{{i.name}}">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" style="color: rgb(43, 83, 197);">Edit Folder Name</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </div>
                <div class="modal-body">
                    <p>Are you sure to rename {{i.name}}?</p>
                
            
                <div class="justify-content-between mb-2 mr-2 text-right">
                    <form method="post" id="item-edit-form" action="{% url 'ftp:folder-rename' pk=i.name%}">
                        {% csrf_token %}
                        <input type="text" class="form-control" name="d_name" placeholder="Enter new folder name here.." required><br>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary mr-1" data-dismiss="modal">Cancel</button>
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary" id="confirm-update-folder-button" value="update">Rename</button>
                    </form>
                </div>
            </div>
            </div>
        </div>
    </div>
</div>
            {% endfor %}

            {% for i in f %}
            <div class="col-sm-6 col-md-4 col-lg-3 col-xl-2">
                <div class="col mr-2">
                    <div style="display: flex; flex-direction: column;">
                        <div class="container">
                            <a class=" dropdown-toggle" href="#" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: azure;">
                                <i class="fa fa-caret-down fa-2x" style="color: #6586E7; position: absolute; left: 60px;" aria-hidden="true"></i>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <a href="{% url 'ftp:delete-file' pk=i.id %}" class="dropdown-item text-danger" data-toggle="modal" data-target="#del{{i.id}}" id="delete-item">              
                                    Delete
                                    <i class="fa fa-trash" aria-hidden="true" ></i>
                                </a>
                                <a href="#" class="dropdown-item text-info" data-toggle="modal" data-target="#edit{{i.id}}" id="edit-item">
                                Edit Name
                                <i class="fas fa-edit"></i>
                                </a>
                            </div>
                        </div>
                        <div>
                        <a href="{{i.file_path}}">
                          {% if i.file_ext == '.txt' %}
                          
                            <i class="fa-solid fa-file-lines" style="font-size: 4rem; color: #6586E7;"></i>
                            {% elif i.file_ext == '.docx' or i.file_ext == '.odt' %}
                            <i class="fa-solid fa-file-word"></i>
                            {% elif i.file_ext == '.pptx' %}
                            <i class="fas fa-file-powerpoint" style="font-size: 4rem; color: #6586E7;"></i>
                            {% elif i.file_ext == '.csv' %}
                            <i class="fas fa-file-csv" style="font-size: 4rem; color: #6586E7;"></i>
                          {% elif i.file_ext == '.pdf' %}
                          <i class="fa-solid fa-file-pdf" style="font-size: 4rem; color: #6586E7;"></i>
                          {% elif i.file_ext == '.mp4' or i.file_ext == '.mpeg-4' or i.file_ext == '.avi' or i.file_ext == '.mov' or i.file_ext == '.mkv'%}
                          <i class="fas fa-video" style="font-size: 4rem; color: #6586E7;"></i>
                          {% elif i.file_ext == '.jpg' or i.file_ext == '.jpeg' or i.file_ext == '.png' or i.file_ext == '.gif'%}
                          <i class="fas fa-image" style="font-size: 4rem; color: #6586E7;"></i>
                          {% elif i.file_ext == '.html' or i.file_ext == '.py' or i.file_ext == '.css' or i.file_ext == '.js' or i.file_ext == '.xml' or i.file_ext == '.json' %}
                          <i class="fas fa-file-code" style="font-size: 4rem; color: #6586E7;"></i>
                          {% elif i.file_ext == '.xls' or i.file_ext == '.xlsx' or i.file_ext == '.xlsm' or i.file_ext == '.xlsb' %}
                          <i class="fas fa-file-excel" style="font-size: 4rem; color: #6586E7;"></i>
                          {% else %}
                          <i class="fa-solid fa-file" style="font-size: 4rem; color: #6586E7;"></i>
                          {% endif %}
                          </a> 
                          
                        </div>
                        
                          <span style="word-wrap: break-word;"> 
                         
                            {{ i.file_name }}
                         
                          </span>
                    
                    </div>
                  </div>
                </div>
              
              <!-- delete modal -->
              <div class="modal fade" id="del{{i.id}}">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" style="color: rgb(43, 83, 197);">File Delete</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                          </div>
                          <div class="modal-body">
                              <p>Are you sure to delete file {{i.file_name}}</p>
                          </div>
                          <div class="modal-footer">
                              <div class="justify-content-between mb-2 mr-2 text-right">
                                  <form method="post" id="item-delete-form" action="{% url 'ftp:delete-file' pk=i.id %}">
                                      <button type="button" class="btn btn-primary mr-1" data-dismiss="modal">Cancel</button>
                                      {% csrf_token %}
                                      <button type="submit" class="btn btn-danger" id="confirm-delete-item-button">Delete</button>
                                  </form>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>    
                  <!-- edit modal -->
                  <div class="modal fade" id="edit{{i.id}}">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" style="color: rgb(43, 83, 197);">Edit File Name</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </div>
                        <div class="modal-body">
                          <p>Are you sure to rename {{i.file_name}}?</p>
                        
                  
                        <div class="justify-content-between mb-2 mr-2 text-right">
                          <form method="post" id="item-edit-form" action="{% url 'ftp:file-rename' pk=i.id %}">
                            {% csrf_token %}
                            <input type="text" class="form-control" name="d_name" placeholder="Enter new name for file here .." required><br>
                            <div class="modal-footer">
                              <button type="button" class="btn btn-secondary mr-1" data-dismiss="modal">Cancel</button>
                              {% csrf_token %}
                              <button type="submit" class="btn btn-primary" id="confirm-update-folder-button"
                                value="update">Rename</button>
                          </form>
                        </div>
                      </div>
                    </div>
                  </div>
                  </div>
              </div>
              
            {% endfor %}
            {% else %}
            <div>No folders or files in trash</div>
            {% endif %}
            {% endblock %}
</div>

ftp/templates/ftp/upload_file.html
{% extends 'ftp/base.html' %}

{% load static %}

{% block content %}
<style>
  .file {
  opacity: 0;
  width: 0.1px;
  height: 0.1px;
  position: absolute;
}
</style>

<div>
<p class="h1">
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
    {% if user.is_authenticated %}
    <a href="{% url 'ftp:dashboard' user.username %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"> Dashboard</a><br>
    {% else %}
    <a href="{% url 'ftp:home' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"> Home</a>
    {% endif %}
  </div>
</p><br>

<form action = "{% url 'ftp:upload' pk %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" id="file" name="myfile">
    <button type="submit">Upload</button>
  </form>

  {% if uploaded_file_url %}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  {% endif %}
{% if user.is_authenticated %}
  <p><a href="{% url 'ftp:dashboard' user.username %}">Return to home</a></p>
{% else %}
<p><a href="{% url 'ftp:home' %}">Return to home</a></p>
{% endif %}
</div>
{% endblock %}